---
ID: "3f796130-2288-4c90-b18e-4f7ff06052cf"
Parent: "51e67dfc-cca5-4283-9157-50d310732f11"
Template: "51e67dfc-cca5-4283-9157-50d310732f11"
Path: /sitecore/templates/Feature/Modules/Module Item/__Standard Values
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T033736Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
