---
ID: "2d3169d9-9630-44cc-b7b7-f78fae5d80f4"
Parent: "b6740bb0-d4dc-4a82-b2c6-7ad99bd9cc0d"
Template: "b6740bb0-d4dc-4a82-b2c6-7ad99bd9cc0d"
Path: /sitecore/templates/Project/Community/Page Design/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T052142Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
