---
ID: "af80a2d0-67fc-4f42-8cec-cf7a42b67afd"
Parent: "b533e93a-4195-454f-ae2a-3dddbbe8231e"
Template: "26fce9bf-0256-458d-8281-a713a5bf5520"
Path: /sitecore/content/Community/Marketplace/Presentation/Cache Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T052436Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
