---
ID: "82012228-72d7-4f7a-b7da-362e417b39f9"
Parent: "4529dd6e-b273-41a1-8819-d55b6a7cf83c"
Template: "4529dd6e-b273-41a1-8819-d55b6a7cf83c"
Path: /sitecore/templates/Data Exchange/Providers/GitHub/Folders/GitHub Value Writers Root/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T142127Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
