---
ID: "9591f3db-4032-4421-8b9a-f93c50a2451b"
Parent: "708ec0e4-221b-4891-bfe6-d6abbe933239"
Template: "708ec0e4-221b-4891-bfe6-d6abbe933239"
Path: /sitecore/templates/Feature/Modules/Product Line/Product Line/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T053910Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
