---
ID: "f5ed1ece-4afe-434a-acd5-e9273af12862"
Parent: "bb3ad616-134b-4b14-8418-712e045371c0"
Template: "bb3ad616-134b-4b14-8418-712e045371c0"
Path: /sitecore/templates/Feature/Modules/Sitecore Versions/Sitecore Version/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T055929Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
