---
ID: "d90dbb3d-aab6-4e1f-89ed-289702427de0"
Parent: "971fcf2b-88d5-40f0-9dba-e2af887c39cc"
Template: "971fcf2b-88d5-40f0-9dba-e2af887c39cc"
Path: /sitecore/templates/Data Exchange/Providers/GitHub/Folders/GitHub Endpoints Root/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T142126Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
