---
ID: "df65c427-1f39-4680-a82f-ed211dc71ec8"
Parent: "5ae7e010-6956-4ab8-a7da-4d989bb83f02"
Template: "6042e216-f650-447c-86d1-00fea97454e7"
Path: /sitecore/content/Community/Marketplace/Settings/Facets/Product Line
DB: master
SharedFields:
- ID: "0e23bb51-c071-41b5-9d83-ac410b89b85a"
  Hint: Parameters
  Value: Product Line
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T203535Z
    - ID: "31ca077f-ef38-4980-8a24-05408031b2bc"
      Hint: Name
      Value: Product Line
