---
ID: "dd937559-cb4d-41f3-9d3d-b0ca81ab1c40"
Parent: "0e2d7c02-efd6-4f51-8fd1-e22520ae1801"
Template: "0e2d7c02-efd6-4f51-8fd1-e22520ae1801"
Path: /sitecore/templates/Project/Community/Tenant/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T052141Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
